### ISSUE TITLE
No readme + how to contribute

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io-library/base-images#1]
There should be a readme for these images, links to the other base architecture images and a short description of how to contribute.

**Comment by nghiant2710** [comment]
@shaunmulligan , I added the readme for this repo and others too. Please review them.
https://github.com/resin-io-library/resin-armhfv7-debian
https://github.com/resin-io-library/resin-rpi-raspbian
https://github.com/resin-io-library/resin-i386-debian
