### ISSUE TITLE
Webterminal throws xargs error on fedora base images

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io-library/base-images#173]
Get the following error when spawning a web terminal using one of our Fedora base images:
```
sh: line 1: xargs: command not found     
```
The terminal still seems to work, so not sure if its an issue or not, it just looks ugly :P

linked to: https://github.com/resin-io/resin-proxy/issues/34

**Comment by petrosagg** [comment]
@nghiant2710 we have to add `findutils` in the list of default packages we install for all base images
