### ISSUE TITLE
New info from systemd printed to logs

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io-library/base-images#188]
In the latest base images I now see additional info printed out when INITSYSTEM=on, this is actually pretty useful info to have, so I think it should be kept, just highlighting this.

<img width="938" alt="screen shot 2016-09-24 at 19 25 31" src="https://cloud.githubusercontent.com/assets/3915043/18869506/83b6f730-84a4-11e6-82f2-fe636257d8c9.png">

**Comment by petrosagg** [comment]
I'm not sure why this started happening, we didn't change anything systemd related. Maybe it was an update.
