### ISSUE TITLE
Consider providing yarn as part of the base image

### ISSUE THREAD

**Issue by emirotin** [resin-io-library/base-images#206]
https://yarnpkg.com/ is a modern npm client replacement from Facebook, Google, et. al.
Providing it pre-packaged is a matter of `npm install -g`, but should make our images look way more modern.
Would probably only make sense for `node >= 4`

**Comment by Page-** [comment]
Do you happen to know how big yarn is? For the sake of the slim images I'd say we should leave it out regardless (should be bare minimum), but it'd be nice to know the cost for other images as well

**Comment by nghiant2710** [comment]
there is a PR for it in official repo https://github.com/nodejs/docker-node/pull/260 but it's not merged yet. We will consider including it when it's approved in upstream repository, I think

**Comment by emirotin** [comment]
OK, it's _not that small_:

```
du -sh ~/.nvm/versions/node/v6.5.0/lib/node_modules/yarn
 24M	/Users/eugene/.nvm/versions/node/v6.5.0/lib/node_modules/yarn
```

As a side not we don't have to wait for the official image change, as I said it can easily be done with a single extra `RUN` command.

**Comment by nghiant2710** [comment]
I meant it's still controversial whether should it be used and how to add it into the base images. So it's better to wait a bit and see how it goes

**Comment by petrosagg** [comment]
@emirotin to give some context, the reason we wait for upstream is because we want to be as aligned as possible with Docker's base images to give our users a familiar environment to work in. Granted this is a pure addition, but still an interface that we'll have to maintain if added.

Regarding the size, ouch :/
