### ISSUE TITLE
Provide Python 3.6 image

### ISSUE THREAD

**Issue by agronholm** [resin-io-library/base-images#222]
The latest Python image is still 3.5.2. It would be nice to have 3.6.0 images too.

**Comment by nghiant2710** [comment]
@agronholm we have it in our plan, python 3.6 base images will be released soon :-)

**Comment by agronholm** [comment]
Thanks! Any ETA?

**Comment by agronholm** [comment]
Ah, I see you already have a PR for this. Nice!

**Comment by nghiant2710** [comment]
@agronholm, added in https://github.com/resin-io-library/base-images/pull/224

**Comment by agronholm** [comment]
Awesome! Any idea when they'll be on Docker Hub?

**Comment by agronholm** [comment]
@nghiant2710 Sorry to bother you, but do you know what the next step is for getting the images to Docker hub? Can I assist somehow?

**Comment by agronholm** [comment]
Never mind, the image is on Docker hub now. Thank you!
