### ISSUE TITLE
Please add support for C.H.I.P. base images

### ISSUE THREAD

**Issue by bcopy** [resin-io-library/base-images#231]
The CHIP is a 9 dollars ARMv7 computer that is debian and alpine compatible (getchip.com) - Adding it to the list of supported platforms would be a quick win.

**Comment by nghiant2710** [comment]
hey @bcopy, thanks for your suggestion, we will add the base images for that board as soon as it's supported by Resin. In the meantime, you can run the generic armv7 base images `resin/armv7hf-debian` or `resin/armhf-alpine`

**Comment by rauston** [comment]
+1, @bcopy, did you get one of the generic armv7 base images to run on the C.H.I.P? If so, which one and are you using the C.H.I.P or C.H.I.P PRO board? Thanks!

**Comment by bcopy** [comment]
Yeah the generic armhf images work fine.

**Comment by nghiant2710** [comment]
@bcopy @rauston please follow the device support progress here https://waffle.io/resin-os/resin-os-device-support or create a request for new board here https://github.com/resin-os/resin-os-device-support.

We will create base images for it as soon as It's supported. In the meantime, you can just use resin generic armhf base images.
