### ISSUE TITLE
Availability of resin/aarch64-alpine:3.5

### ISSUE THREAD

**Issue by harshavardhana** [resin-io-library/base-images#246]
Is there a reason why https://github.com/resin-io-library/base-images/tree/master/alpine/aarch64/3.5 - is not available hub.docker.com yet?

**Comment by nghiant2710** [comment]
Hi @harshavardhana,

Thanks for reporting this, there's an issue with our automation build system. I've resolved it and the images are now available on docker hub.

**Comment by harshavardhana** [comment]
> Thanks for reporting this, there's an issue with our automation build system. I've resolved it and the images are now available on docker hub.

Oops i just saw :+1: - thanks a bunch.
