### ISSUE TITLE
Unable to launch interactive shell when running the container locally

### ISSUE THREAD

**Issue by nghiant2710** [resin-io-library/base-images#250]
With the current implementation https://github.com/resin-io-library/base-images/blob/master/debian/entry.sh#L84-L86, we will never be able to start an interactive shell when running the container locally, the reason is CMD will be started in background so command like `docker run -it resin/raspberrypi3-debian:jessie /bin/bash` won't work as expected. This is really bad since our base images are widely used by Docker community.

Adding `fg` command after having run `wait $pid` is the solution here but there is another issue since ` `fg` always returns exit code 1 if there is no background process to attach to so we need a way to pass the correct exit code in that case.

There were few PRs to fix this issue:
https://github.com/resin-io-library/base-images/pull/186 (https://github.com/resin-io-library/base-images/commit/b18bd44badeccae9cf7b549c96b6fcb2f861bfdc)
https://github.com/resin-io-library/base-images/pull/191 (https://github.com/resin-io-library/base-images/commit/b789b41f43b5d92d069e2ec0878f0b130c90947a)
https://github.com/resin-io-library/base-images/pull/227 (https://github.com/resin-io-library/base-images/commit/4be4d71862db662c603aa090ed2d8f9ac69d5c96)
but none of them completely solves this.

This PR https://github.com/resin-io-library/base-images/pull/238 will address all the problems that relate to this issue.

**Comment by petrosagg** [comment]
The description talked about linked PRs but there are linked commits.

The last commit link doesn't work

**Comment by nghiant2710** [comment]
Sorry for that, here are the PRs https://github.com/resin-io-library/base-images/pull/186, https://github.com/resin-io-library/base-images/pull/191 and https://github.com/resin-io-library/base-images/pull/227. I've updated the description here to explain more about this issue.
