### ISSUE TITLE
Broken interactive shell when run image locally

### ISSUE THREAD

**Issue by nghiant2710** [resin-io-library/base-images#284]
To fix this issue https://github.com/resin-io-library/resin-rpi-raspbian/issues/56, we redirected `fg` stderr to `/dev/null' however it's not a good fix since it breaks interactive shell when run the image locally.

We need to address this issue asap because it's being used as a base by most of the Docker/ARM community.

**Comment by qr-dev** [comment]
Hi,
Running most commands is possible (tried ls, etc...) but since recently running /bin/bash exits directly. 
I use this option often to troubleshoot containers :-(

docker run -it resin/rpi-raspbian:latest /bin/bash

Hope you can fix this.

**Comment by nghiant2710** [comment]
Fixed in https://github.com/resin-io-library/base-images/pull/237
