### ISSUE TITLE
Alpine 3.6 images

### ISSUE THREAD

**Issue by imrehg** [resin-io-library/base-images#286]
[Alpine 3.6 was released](https://www.alpinelinux.org/posts/Alpine-3.6.0-released.html) recently, would be great to have such variants as well for the `-alpine` images :)

I guess it depends on [armhf/alpine](https://hub.docker.com/r/armhf/alpine/) having a 3.6 release.

**Comment by nghiant2710** [comment]
Alpine 3.6 added https://github.com/resin-io-library/base-images/commit/1beab8f97f59d6a1e1d0f75d0faa067f23fe4c9d.
