### ISSUE TITLE
Is MPTCP (MultiPath TCP) support in the current kernel in the base images?

### ISSUE THREAD

**Issue by reedog117** [resin-io-library/base-images#304]
I'm creating an app that relies on multiple outbound connections (WiFi/Cellular) to ensure that data is transferred robustly.  Is MPTCP (now making its debut on mobile devices like in iOS 11 and some Samsung phones in Korea) support compiled into the kernel or are there methods of getting that support in a container?

**Comment by nghiant2710** [comment]
@reedog117 So sorry for the late response but I think your question should be raised in our resinos repository https://github.com/resin-os/resinos.
