### ISSUE TITLE
Python 3.3+ base images missing lzma

### ISSUE THREAD

**Issue by jasl8r** [resin-io-library/base-images#320]
Python 3.3 introduces lzma into the standard library, but it is only compiled if lzma is installed in the base image.  See the same issue with the alpine python image from last year here: https://github.com/docker-library/python/issues/86

**Comment by nghiant2710** [comment]
@jasl8r we've added the missing libs to our python build script https://github.com/resin-io/python-build/commit/0896eb0c85c91c91f6c3b4bbece556d027e44670 and will rebuild all Python binaries. I will let you know once it's done

**Comment by nghiant2710** [comment]
fixed in https://github.com/resin-io-library/base-images/pull/328
