### ISSUE TITLE
libmraa on Edison isn't versioned

### ISSUE THREAD

**Issue by petrosagg** [resin-io-library/base-images#34]
We should pin a specific version for libmraa and update it whenever we see fit here https://github.com/resin-io-library/base-images/blob/master/device-base/Dockerfile.i386.edison.tpl#L22-L26.

The current version of the library is v0.8.1.

**Comment by nghiant2710** [comment]
fixed in https://github.com/resin-io-library/base-images/commit/5ba2f11a7934001b82799f7b56c67abac1303e32
