### ISSUE TITLE
libmraa build dependencies are installed forever

### ISSUE THREAD

**Issue by petrosagg** [resin-io-library/base-images#35]
The build dependencies in the device base image for the edison should be cleaned up after use just like we'd do with a slim image. Otherwise even the slim images for the Edison won't be as slim.

https://github.com/resin-io-library/base-images/blob/master/device-base/Dockerfile.i386.edison.tpl#L4-L18

**Comment by nghiant2710** [comment]
fixed in https://github.com/resin-io-library/base-images/commit/5ba2f11a7934001b82799f7b56c67abac1303e32
