### ISSUE TITLE
standard_init_linux.go:187: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by bg172** [resin-io-library/base-images#393]
When executing 
`docker run --rm -it resin/rpi-raspbian uname -a`
in Ubuntu (tried 17.10 with Docker version 1.13.1, build 092cba3 and Docker version 18.02.0-ce, build fc4de44, 
also Ubuntu and 16.04 with Docker version 1.13.1, build 092cba3) after the expected pull part: 
`latest: Pulling from resin/rpi-raspbian`
`98f918e3af87: Pull complete `
`6cee82f64495: Pull complete `
`b4560f2579a7: Pull complete `
`cfb1f0837526: Pull complete `
`892099c39229: Pull complete `
`fb54b7fcccee: Pull complete `
`b5b1ce137279: Pull complete `
`7ec4f2a843eb: Pull complete `
`138a76d14743: Pull complete `
`71d85adc2ecb: Pull complete `
`9b7f7bd1e39d: Pull complete `
`Digest: sha256:83306205e98acd31f2e6cc4f6f660b3370561f952dfc273436269ad5c1534068`
`Status: Downloaded newer image for resin/rpi-raspbian:latest`
the following error occurs
`standard_init_linux.go:195: exec user process caused "no such file or directory"`

More info about the used Ubuntu17.10:
cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
VERSION_ID="17.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

uname -a:
Linux abcpc 4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nghiant2710** [comment]
@bg172, the `resin/rpi-raspbian` is an ARM image, you can't just run it on x86_64 environment. We have a blog post about running ARM on x86 machines which might be useful for you https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/.
