### ISSUE TITLE
Is it possible to make the alpine images smaller?

### ISSUE THREAD

**Issue by benhowes** [resin-io-library/base-images#403]
The alpine images still seem to be pretty large! is it possible to make them smaller?

```
$> docker images
REPOSITORY                              TAG                 IMAGE ID            CREATED             SIZE
resin/raspberrypi3-alpine-python        latest              9cafdfc04b23        4 hours ago         465MB
resin/raspberrypi3-python               latest              77f135ba7342        22 hours ago        480MB
```

**Comment by nghiant2710** [comment]
@benhowes, that image is pretty large since it's based on our `buildpack-deps` image which has all the essential tools and common libraries. You can select the `slim` version which is smaller https://hub.docker.com/r/resin/raspberrypi3-alpine-python/tags/
