### ISSUE TITLE
Beaglebone Black Node Base Image systemd Broken

### ISSUE THREAD

**Issue by esetnik** [resin-io-library/base-images#452]
```
31.07.18 12:15:29 (-0400)  main  Systemd init system enabled.
31.07.18 12:15:29 (-0400)  main  Failed to insert module 'kdbus': Function not implemented
31.07.18 12:15:29 (-0400)  main  systemd 230 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
31.07.18 12:15:29 (-0400)  main  Detected virtualization docker.
31.07.18 12:15:29 (-0400)  main  Detected architecture arm.
31.07.18 12:15:29 (-0400)  main  Set hostname to <788b700>.
31.07.18 12:15:29 (-0400)  main  Cannot determine cgroup we are running in: No medium found
31.07.18 12:15:29 (-0400)  main  Failed to allocate manager object: No medium found
31.07.18 12:15:29 (-0400)  main  [!!!!!!] Failed to allocate manager object, freezing.
31.07.18 12:15:29 (-0400)  main  Freezing execution.
```
It is broken in the latest [resin/beaglebone-black-node:8-slim](https://github.com/resin-io-library/base-images/blob/master/node/beaglebone-black/debian/8.11/slim/Dockerfile) as well as all other variants I was able to test such as `node:8`, `node`, `node:6-slim`, `node:6` and originally reported in https://github.com/resin-io-projects/simple-server-node/issues/16.

It seems to be related to https://github.com/resin-io-library/resin-rpi-raspbian/issues/75 and was supposedly fixed in https://github.com/resin-io-library/base-images/pull/342.

**Comment by nghiant2710** [comment]
Sorry for the latest response, a wrong version systemd was installed that caused this issue. We fixed the beaglebone images and they will work properly now.
