### ISSUE TITLE
Modprobe not found [rpi-raspbian:buster]

### ISSUE THREAD

**Issue by tomsimonart** [resin-io-library/base-images#471]
When using buster as image tag I can't use `modprobe` in my Dockerfile

Dockerfile contains:
`CMD ["modprobe", "mymodule"]`

Error after building image:

> /etc/resinApp.sh: line 2: exec: modprobe: not found

or

`CMD modprobe mymodule`

gives me this as a result:

> /bin/sh: 1: modprobe: not found

**I don't have this bug at all when using jessie** for example.

I don't understand if this is a permission problem or something else
My guess is that it has something to do with the default `privileged: true` passing for whatever reason to `false`

Thanks for taking the time :+1:

**Comment by nghiant2710** [comment]
@tomsimonart, I think `kmod` is missing here. We use debootstrap to build the raspbian image so probably `kmod` is no longer pre-installed in raspbian buster. Please manually install `kmod` for now until we fix this issue. Thanks a lot for your report,
